package com.breakbooking.repo;


import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDate;


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import com.breakbooking.model.Customer;

@DataJpaTest
class CustomerRepoTest {

	@Autowired
	private CustomerRepo underTest;
	
	@BeforeEach
	void setUp() throws Exception {
	}

	@AfterEach
	void tearDown() throws Exception {
		underTest.deleteAll(); // After each test I want to delete all
	}

	@Test
	void itShouldSelectExistsEmailFound() {
		//Given
		Customer customer=new Customer(
				1L,
				"Shwetali",
				"shwetalishine@gmail.com",
				"Developer",
				"678345768",
				LocalDate.of(2000, 06, 06),
				"Anything",
				"AutoGeneratedCustomerCode"
				);
		underTest.save(customer);
				
		//When
		String email="shwetalishine@gmail.com";
		boolean expected=underTest.selectExistsEmail(email);
		//Then
		assertThat(expected).isTrue();
	}
	

	@Test
	void itShouldSelectExistsEmailNotFound() {
		//Given
	
		String email="shwetalishine@gmail.com";
		
		//When
		
		boolean expected=underTest.selectExistsEmail(email);
		
		//Then
		
		assertThat(expected).isFalse();
	}

}
